server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    healthcheck:
      enabled: true
    fetchRegistry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/